change lazy loading library to have 'src' in img tags for accessibility
betagouv/beta.gouv.fr pull request #10106
Opened 2022-05-30 09:55 UTC by lisa-durand

Les images n’ont pas de src, parce qu’elles utilisent un attribut data-src à la place, utilisé par la librairie de lazy-loadind https://apoorv.pro/lozad.js/. 
On a donc remplacé cette librairie par une autre librairie.

2022-05-31 12:35 UTC, freesteph approved these changes

2022-05-31 12:35 UTC, freesteph commented on assets/additional/js/accessible-image-lazy-load.js
> +/*! accessible-image-lazy-load v1.3.2 (c) 2020 Jorge Moreno, moro.es (@alterebro) https://moro.es/projects/gandul-accessible-image-lazy-loading/ */
Est-il possible d'avoir la librairie dans notre `package.json` via NPM plutôt ? Comme ça on n'a pas à maintenir la librairie en parallèle.

2022-05-31 12:35 UTC, freesteph commented on assets/additional/js/search-member.js
> +          gandul();
on peut avoir ça sur le base layout plutôt ?

2022-05-31 12:35 UTC, freesteph commented on assets/additional/js/search-member.js
> +          gandul();
on peut avoir ça sur le base layout plutôt ?

2022-05-31 12:35 UTC, freesteph requested changes

2022-05-31 12:36 UTC, freesteph commented
Désolé me suis trompé de décision 😄 ; j'aimerais qu'on tacle l'histoire de NPM + le loading avant de merge.

2022-05-31 15:32 UTC, freesteph commented on _includes/script.html
> +<script>gandul();</script>
je me demande s'il n'est pas mieux d'initialiser gandul sur un évènement de la fenêtre genre `DOMContentLoaded` sinon il peut manger du contenu ?

2022-05-31 15:37 UTC, lisa-durand commented on assets/additional/js/search-member.js
> +        // call Lazy loading (accessible-image-lazy-load.js)
alors si malheureusement c'est nécessaire sinon ça ne fonctionne pas.
Je te laisse tester en local ? En gros l'idée est d'aller sur la page annuaire ou réalisation et utiliser le filtre.

2022-05-31 15:54 UTC, freesteph commented on assets/additional/js/search-member.js
> +        // call Lazy loading (accessible-image-lazy-load.js)
d'acc je vais regarder ; étrange car l'annuaire utilise le layout `default` qui charge `include/script` qui lui même initialise `gandul`?

2022-07-05 12:20 UTC, freesteph commented
remplacée par #10606

2022-07-05 12:20 UTC, closed without merging