A11y/add lazy load placeholder
betagouv/beta.gouv.fr pull request #10606
Opened 2022-06-30 14:04 UTC by freesteph

Pour éviter des images au marquage invalide (i.e pas d'attribut `src`), on met un placeholder en `src` avant que lozad puisse éventuellement remplacer l'image en lazy-load.

J'en ai profité pour bouger ce code d'avatar/screenshot dans des filtres custom qui permettent d'éviter le markup spaghetti qui les précédait.

2022-07-01 14:22 UTC, lisa-durand requested changes
Très cool cette PR avec l'extraction de la logique des vues - bcp plus lisible !
Ça corrige aussi en passant les `title` qui n'avaient pas leur place sur les images - bien joué !

Je t'ai fait un petit commentaire sur le `force=true` qui traine et d'un point de vue plus fonctionnelle, il serait intéressant d'avoir un placeholder tres neutre - gris comme tu le suggerais - à mettre par défaut dans le `src` pour toutes les images (ça éviterait le clignotement bleu/blanc/rouge avant que les images se chargent) et on pourrait ensuite avoir le placeholder "beta" pour les startups ou avatar sans image. On peut en rediscuter lundi lors de notre point si vous voulez :)

2022-07-01 14:22 UTC, lisa-durand commented on _includes/screenshot.html
> +S'appelle avec une startup. On peut spécifier force=true pour forcer une image.
Ici tu as laissé le commentaire sur `force=true` alors qu'il n'est plus utilisé dans les filtres (à raison 👍 )- il faudrait donc le retirer ainsi que dans les appels de l'include en question.

2022-07-01 14:22 UTC, lisa-durand commented on _layouts/lpintra.html
> +                  <img src="/assets/images/intra/join.png" alt="">
👌

2022-07-04 07:15 UTC, freesteph commented on _includes/screenshot.html
> +S'appelle avec une startup. On peut spécifier force=true pour forcer une image.
bien vu merci

2022-07-04 15:11 UTC, lisa-durand commented
@freesteph top pour le retrait du force true. Par contre tu as laissé les place holder de `src` par défaut avec l'image  bleu-blanc-rouge, elles apparaissent avant le remplacement des "vrais images" et ça fait une sorte de clignotement pas ouf.

2022-07-05 11:04 UTC, freesteph commented
> @freesteph top pour le retrait du force true. Par contre tu as laissé les place holder de `src` par défaut avec l'image bleu-blanc-rouge, elles apparaissent avant le remplacement des "vrais images" et ça fait une sorte de clignotement pas ouf.

C'est ce dont je voulais discuter au point a11y mais finalement en comparant les deux versions (actuelle sur beta.gouv.fr, et le nouveau lazy-load en local) je trouve que la nouvelle version est toujours mieux que l'ancienne qui n'a pas d'image et qui change de taille à chaque chargement d'image. Qui plus est l'image de placeholder est aussi celle par défaut s'il n'y a pas d'image réelle donc ça évite potentiellement plein de flashs en plus.

2022-07-05 12:17 UTC, rebeccadumazert commented
> > @freesteph top pour le retrait du force true. Par contre tu as laissé les place holder de `src` par défaut avec l'image bleu-blanc-rouge, elles apparaissent avant le remplacement des "vrais images" et ça fait une sorte de clignotement pas ouf.
> 
> C'est ce dont je voulais discuter au point a11y mais finalement en comparant les deux versions (actuelle sur beta.gouv.fr, et le nouveau lazy-load en local) je trouve que la nouvelle version est toujours mieux que l'ancienne qui n'a pas d'image et qui change de taille à chaque chargement d'image. Qui plus est l'image de placeholder est aussi celle par défaut s'il n'y a pas d'image réelle donc ça évite potentiellement plein de flashs en plus.

Je sais pas si j'ai bien compris ta réponse @freesteph, mais on se disait qu'avec un placeholder gris de la même couleur de la card ça ferait moins une sensation de clignotement. Sinon j'approuve cette PR

2022-07-05 12:17 UTC, rebeccadumazert approved these changes

2022-07-12 14:41 UTC, lisa-durand reviewed
D'un point de vue fonctionnel j'ai l'impression qu'il y a tjs : 
- l'apparition du placeholder bleu blanc rouge qui clignote quand on utilise les filtres pour les startups
- les cards de l'annuaire n'ont pas l'air de se servir du placeholder car on a tjs l'effet de la carte qui s'agrandit d'un coup car pas d'image au chargement

2022-07-12 14:41 UTC, lisa-durand commented on assets/additional/js/search-startup.js
> +const STARTUP_PLACEHOLDER = "/img/betagouv-rectangle.png";
du coup si tu mets ça - ça refait le clignotement quand on utilise les filtres non ?

2022-07-12 14:57 UTC, freesteph commented on assets/additional/js/search-startup.js
> +const STARTUP_PLACEHOLDER = "/img/betagouv-rectangle.png";
ah bien vu j'ai oublié ce code de l'enfer – je m'en occupe

2022-07-13 07:27 UTC, lisa-durand approved these changes
c'est top !

2022-07-13 12:22 UTC, merged