supprime certaines descriptions des alt sur les img && ajoute des titres pour mieux structurer page
betagouv/beta.gouv.fr pull request #10659
Opened 2022-07-04 14:39 UTC by rebeccadumazert

J'ai supprimé la plupart des descriptions alt des icon car ce n'est pas une bonne pratique de mettre "illustration" dans les alt puisque une img vient presque forcément illustrer quelque chose. Quand une img est décorative un alt vide est valide. 

J'ai laissé la description de la photo.

J'ai remis en ordre trois titres pour ce que soit mieux structuré (je l'avais pas fait dans mon ancienne PR !)

2022-07-04 14:40 UTC, rebeccadumazert commented
et j'ai fait un rebase, il date avant notre réunion et il ne devrait pas trop être hardcore pour la relecture j'espère

2022-07-05 08:33 UTC, lisa-durand requested changes
N'ayons pas peur du "request changes" 😅 
C'est top - je t'ai fait qq commentaires :)

2022-07-05 08:33 UTC, lisa-durand commented on _layouts/brigade.html
> +             alt="La communauté beta.gouv.fr au séminaire de septembre 2021" />
je pense que tu peux aussi "vider" ce `alt` là. Cette image est purement décorative à mon sens, car elle n'apporte rien en terme de compréhension sur la page.

2022-07-05 08:33 UTC, lisa-durand commented on assets/main.css
> -.phase-description {
pourquoi ce bout de CSS disparait ?
Il ne semble pas hyper primordial - mais du coup il faudrait aussi le supprimer dans la page `startup` ou il est utilisé.

2022-07-05 08:50 UTC, freesteph requested changes
Juste le CSS enlevé qui est encore utilisé (`.phase-description`) sinon all good 👍

2022-07-05 08:50 UTC, freesteph commented on _layouts/brigade.html
> +             alt="La communauté beta.gouv.fr au séminaire de septembre 2021" />
L'image apporte de la sémantique ; elle s'inscrit dans la description de la communauté, donc je pense que le `alt` est pertinent.

https://www.w3.org/WAI/tutorials/images/informative/

2022-07-06 15:21 UTC, freesteph approved these changes

2022-07-06 15:24 UTC, lisa-durand approved these changes

2022-07-06 15:41 UTC, merged