ajoute titres pour rendre la hiérarchie correcte
betagouv/beta.gouv.fr pull request #10699
Opened 2022-07-08 09:23 UTC by rebeccadumazert

Je remplace des `<p>` par des `<h2>` afin de hiérarchiser correctement l'information.

2022-07-08 10:02 UTC, lisa-durand requested changes
De manière plus globale, je pense qu'il faut revoir un peu la hierarchie des titres, voici une proposition : 
- ajouter un h1 unique à la page "Nos réalisations" par exemple
- passer les noms de "phase" en h2 (au lieu de h1) - il faudrait trouver un nom de phase pour "réalisation" du coup. Peut-être se rapprocher d' @IshanB ? ou autre personne qui gère plus le contenu du site ?
- laisser la description de la "phase" de type `<p>`
Qu'en penses-tu ?

2022-07-08 10:39 UTC, lisa-durand commented
Sur le même modèle qu'on a "X services en transfert" on pourrait avoir "X services pérennisés" au lieu de "nos réalisations" qui deviendrait le titre global de la page ?
@Flightan @IshanB @astranchet

2022-07-08 12:29 UTC, astranchet commented
D'accord avec @lisa-durand pour aller plus loin dans la hiérarchie des titres. Aujourd'hui, on a : 
![image](https://user-images.githubusercontent.com/1374389/177992193-976d90df-2f39-4183-9cd4-8e0cc93268db.png)

Ça serait plus pertinent d'avoir : 
- h1. Nos réalisations
- h2. X services pérénisés
- h3. Anotéa... (et encore, celà c'est pas choquant s'ils ne sont pas des headings je pense)
- h2. X services en transfert
- ...

2022-07-08 16:32 UTC, IshanB commented
La rubrique "Nos réalisations" comporte (en théorie) les produits sortis d'incubation, qui sont des partenariats passés de beta.gouv, mais que nous souhaitons mettre en avant car ce sont des réalisations de beta.gouv qui continuent à suivre les bonnes pratiques.

On souhaitait avec @valentinbrel modifier la section pour y présenter uniquement les produits considérés comme "à impact national", ce qui permettrait de mettre en avant les produits les plus impactants du portefeuille. (Critères d'un service à impact national : https://doc.incubateur.net/communaute/gerer-sa-startup-detat-ou-de-territoires-au-quotidien/la-vie-dune-se/acceleration/services-numeriques-a-impact-national?q=service+%C3%A0+impact+national) 

"XX services pérennisés" est un peu faux, car dans la section "Partenariats passés", il y a aussi des services qui ont été pérennisés. 
Option 1 : "XX services à impact national" mais ça n'est pas très clair pour l'utilisateur à mon avis
Option 2 : on est obligé de garder le décompte ? On pourrait parler des "Services à la une" par exemple ? 
Preneur d'autres idées

2022-07-08 19:05 UTC, astranchet commented
Tu as raison, je pense que la mention du nombre de SE n’est clairement pas utile pour l’utilisateur externe à beta (mais par contre très utile pour les membres de la communauté, surtout celles et ceux ayant une activité transverse. Du coup, il faudrait garder l’information quand même, le site servant ces 2 cibles)

Anne-Sophie
Le 8 juil. 2022 à 18:32 +0200, Ishan Bhojwani ***@***.***>, a écrit :
> La rubrique "Nos réalisations" comporte (en théorie) les produits sortis d'incubation, qui sont des partenariats passés de beta.gouv, mais que nous souhaitons mettre en avant car ce sont des réalisations de beta.gouv qui continuent à suivre les bonnes pratiques.
> On souhaitait avec @valentinbrel modifier la section pour y présenter uniquement les produits considérés comme "à impact national", ce qui permettrait de mettre en avant les produits les plus impactants du portefeuille. (Critères d'un service à impact national : https://doc.incubateur.net/communaute/gerer-sa-startup-detat-ou-de-territoires-au-quotidien/la-vie-dune-se/acceleration/services-numeriques-a-impact-national?q=service+%C3%A0+impact+national)
> "XX services pérennisés" est un peu faux, car dans la section "Partenariats passés", il y a aussi des services qui ont été pérennisés.
> Option 1 : "XX services à impact national" mais ça n'est pas très clair pour l'utilisateur à mon avis
> Option 2 : on est obligé de garder le décompte ? On pourrait parler des "Services à la une" par exemple ?
> Preneur d'autres idées
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.Message ID: ***@***.***>

2022-07-13 14:37 UTC, IshanB commented
Dans ce cas, je pense que le meilleur compromis est "XX services pérennisés" (pour éviter de parler de Services publics à impact national qui est du jargon interne)

2022-07-13 16:03 UTC, rebeccadumazert commented
@IshanB @lisa-durand @astranchet j'ai repris vos remarques, en effet ça semble bien plus propre comme ça. Merci pour vos retours ! Dites moi si vous voyez d'autres modifs à apporter

2022-07-19 09:44 UTC, Flightan approved these changes

2022-07-19 11:43 UTC, Flightan commented
J'ai aussi fait https://github.com/betagouv/beta.gouv.fr/pull/10781 qui est une PR un peu liée à ce sujet.

2022-07-19 13:21 UTC, lisa-durand commented on _layouts/startups.html
> +                <h2 class="phase-title"><em><span class="phase-counter">{{ counter }}</span></em> {{ phase.type_label }}{{ plural }} <em><span class="phase-label">{{ phase.label | downcase }}</span><
je simplifierai en retirant les `em` et les `span`et la classe attachée qui n'existe plus `phase-label`.
En ayant juste un h2 tout simple - plutot que plusieurs styles sur le titre.

Je retirerai aussi la class `phase-title` du HTML et du CSS.
En gros un bon h2 classique :)

2022-07-19 15:49 UTC, rebeccadumazert commented on _layouts/startups.html
> +            <p class="fr-h6">{{ phase.short_description }}.</p>
carrément, j'enlève ça

2022-07-19 15:57 UTC, rebeccadumazert commented on _layouts/startups.html
> +                <h2 class="phase-title"><em><span class="phase-counter">{{ counter }}</span></em> {{ phase.type_label }}{{ plural }} <em><span class="phase-label">{{ phase.label | downcase }}</span><
Allez, parfois faut pas chercher midi à quatorze heures

2022-07-21 07:27 UTC, freesteph approved these changes

2022-07-25 07:50 UTC, lisa-durand approved these changes
top !

2022-07-25 09:13 UTC, merged