Ajoute une sommaire description du GIP Inclusion
betagouv/beta.gouv.fr pull request #11925
Opened 2022-11-16 15:00 UTC by guillett

Explicite Groupement d'Intérêt Public.

2022-11-16 18:22 UTC, adenoix commented
Merci pour l'initiative ! Je passe la balle à Fanny pour le texte de description (elle bosse sur un truc similaire sur LinkedIn)

2022-11-18 10:25 UTC, FannyDauchez requested changes
La Plateforme de l’inclusion développe de nouveaux services publics pour faciliter la vie des personnes en insertion et de celles et ceux qui les accompagnent. 
Ses missions: 
* Améliorer l’expérience d'accompagnement 
* Faciliter l'accès aux informations utiles sur les parcours et l’offre d'insertion
* Eclairer les politiques publiques avec des données utiles

2022-11-18 13:32 UTC, adenoix approved these changes

2022-11-18 13:34 UTC, merged

2022-11-21 09:38 UTC, FannyDauchez commented on content/_incubators/gip-inclusion.md
> +La Plateforme de l’inclusion développe et améliore services publics pour faciliter la vie des personnes en insertion et de celles et ceux qui les accompagnent.
des