Actualisation de la page de contact
betagouv/beta.gouv.fr pull request #16484
Opened 2023-11-17 08:43 UTC by astranchet

- Page de contact plus simple
- Redirection vers cette page quand nécessaire
- Suppression d'occurence à des emails obsolètes (alpha@beta.gouv.fr, gamma@beta.gouv.fr)

et création d'un SPLENDIDE petit include pour les boutons (pink @sneko)

2023-11-17 12:14 UTC, sneko commented
@astranchet nickel, juste qu'il y a "Nous contacter" en double, et que ce n'est pas dans un encart séparé comme sur la maquette.

<img width="965" alt="image" src="https://github.com/betagouv/beta.gouv.fr/assets/8195958/e73865fd-351f-4f6c-9789-876507bebb84">

<img width="1474" alt="image" src="https://github.com/betagouv/beta.gouv.fr/assets/8195958/6b10ec52-4f87-44f2-9544-1d0e23fbe858">

Sinon pour le reste, good :)

2023-11-17 12:16 UTC, sneko requested changes
cf. commentaire au-dessus

2023-11-17 16:26 UTC, sneko approved these changes
Good to me :)

2023-11-20 15:12 UTC, astranchet commented
@sneko j'ai poussé 2 autres commits (dont un qui mériterait ensuite qu'on repasse sur d'autres templates pour utiliser plus souvent des includes)

2023-11-21 15:29 UTC, merged