Mise à jour de l'API startups
betagouv/beta.gouv.fr pull request #17358
Opened 2023-12-18 16:08 UTC by astranchet

Passage de la 1.7 à la 2.5 : maintenant, on donne des infos stats, d'accessibilité et tout ça.

2023-12-18 16:18 UTC, sneko requested changes

2023-12-18 16:18 UTC, sneko commented on _layouts/dashboard.html
> +                            <td><a href="/startup/{{ startup.id }}">{{ startup.title }}</a></td>
@astranchet les tests ne passent pas, ça rend :
> internally linking to /startup//startups/solution.audiovisuelle.easi, which does not exist

Juste avoir `{{ startup.id }}` devrait être bon

2023-12-19 07:58 UTC, astranchet commented
@sneko bien vu, j'ai corrigé et les tests passent

2023-12-19 09:46 UTC, sneko approved these changes

2023-12-19 09:46 UTC, merged