Remove twitter from footer
betagouv/beta.gouv.fr pull request #17571
Opened 2024-01-03 14:22 UTC by astranchet

2024-01-03 22:38 UTC, sneko requested changes
Je ne sais pas pourquoi les tests ont passé vu que tu as enlevé `twitter_username` et qu'il est utilisé dans https://github.com/betagouv/beta.gouv.fr/blob/ec9d9f419b5bb943d26706456bfda6addb93b196/_includes/head.html#L67-L72

Je pense qu'il faudrait que tu enlèves aussi ces passages liés à Twitter, non ?

2024-01-04 08:33 UTC, astranchet commented
Bien vu @sneko ! 

- Il faut qu'on garde les Open Graphs, qui permettent de faire une "belle" prévisualisation sur les réseaux
- Mais le champ `twitter:site` semble obligatoire [d'après la doc](https://developer.twitter.com/en/docs/twitter-for-websites/cards/overview/markup), hors on en a plus.

J'avoue que je connais mal OpenGraph du coup, quelles lignes doit-on mettre si on a pas de compte Twitter ? Est-ce que ça va marcher avec juste le contenu générique ? 
```
<meta name="thumbnail" content="{{ site.url }}{{ mastheadImagePath }}">
    <meta property="og:image" content="{{ site.url }}{{ mastheadImagePath }}">
```

2024-01-04 09:45 UTC, sneko commented
@astranchet il me semble que la plupart des balises génériques `og:` déjà mises vont faire le taff.

Twitter, Facebook&co les prennent en fallback quand il n'y a pas de spécificités pour leur propre plateforme (des fois utiles si des fomats utilisés est différents, où l'aperçu du texte plus courte (ou non) dans leurs cards.

2024-01-04 15:32 UTC, sneko approved these changes

2024-01-04 15:34 UTC, merged