chore: add incubator logo and filter
betagouv/beta.gouv.fr pull request #20745
Opened 2024-09-12 13:22 UTC by LucasCharrier

## Modification des fiches

Attention, le contenu fiches startup, membre et incubateur **n'est plus modifiable directement sur GitHub**, tu dois exclusivement utiliser [l'espace-membre](https://espace-membre.incubateur.net).

Les changements sont publiés sur le site sous 24h max.

2024-09-13 09:00 UTC, freesteph requested changes

2024-09-13 09:00 UTC, freesteph commented on _plugins/images.rb
> +# ../img/incubators/{{ page.logo }}
🧹

2024-09-13 09:00 UTC, freesteph commented on _plugins/images.rb
> +      return FALLBACK if incubator.nil?
je pense que tu peux enlever ça, je vois pas en quel cas l'incubateur serait pas présent

2024-09-13 09:00 UTC, freesteph commented on _plugins/images.rb
> +      }
t'es le premier à faire ça ! 😄 

On a `activemodel`, donc `activesupport` qui fournit [`String.parameterize`](https://guides.rubyonrails.org/active_support_core_extensions.html#parameterize). 

Et ça devrait être dans la fonction `incubator_id` plutôt qu'ici je pense

2024-09-13 09:00 UTC, freesteph commented on _plugins/images.rb
> +      URLChecker.url_exists?(s3_url) ? s3_url : incubator_file(incubator) || FALLBACK
tu peux mettre ça dans une fonction genre `incubator_s3_img` comme ça après on peut avoir : 

```rb
incubateur_s3_img(incubator) || incubator_file_img(incubator) || FALLBACK
```

2024-09-13 09:00 UTC, freesteph commented on _plugins/images.rb
> +      id = incubator_id(incubator)
pas utilisé je crois

2024-09-16 07:17 UTC, LucasCharrier commented on _plugins/images.rb
> +      return FALLBACK if incubator.nil?
```suggestion
```

2024-09-16 07:18 UTC, LucasCharrier commented on _plugins/images.rb
> +# ../img/incubators/{{ page.logo }}
```suggestion
```

2024-09-16 07:19 UTC, LucasCharrier commented on _plugins/images.rb
> +    end
```suggestion
```

2024-09-16 07:22 UTC, LucasCharrier commented on _plugins/images.rb
> +      id = incubator_id(incubator)
```suggestion
```

2024-09-16 07:22 UTC, LucasCharrier commented on _plugins/images.rb
> +# ../img/incubators/{{ page.logo }}
```suggestion
```

2024-09-16 07:23 UTC, LucasCharrier commented on _plugins/images.rb
> +      return FALLBACK if incubator.nil?
```suggestion
```

2024-09-16 07:48 UTC, LucasCharrier commented on _plugins/images.rb
> +      return FALLBACK if incubator.nil?
je le remet en fait si il y en a besoin, il y peut être un soucis ailleurs, mais j'ai pas le temps d'investiguer plus.

2024-09-16 15:21 UTC, LucasCharrier commented on _plugins/images.rb
> +require 'activesupport'
@freesteph si tu v
```suggestion
require 'active_support/core_ext/string'
```

2024-09-20 13:25 UTC, freesteph approved these changes
Toujours un peu inquiet de cette solution pour le moins engagée mais let's roll

2024-09-20 13:25 UTC, freesteph commented on _layouts/incubateur.html
> +{% unless incubator  %}
tu sais dans quel cas il n'est pas présent ?

2024-09-20 13:25 UTC, freesteph commented on _plugins/images.rb
> +
serait cool de virer les newlines n+1

2024-09-23 08:16 UTC, merged