Demande de Stanislas Ormières
betagouv/beta.gouv.fr pull request #4314
Opened 2020-09-24 13:03 UTC by laruiss

Responsable technique au Lab-MI (Bureau de l'innovation du Ministère de l'Intérieur)

Merci de contribuer au site de beta.gouv.fr ! 

🙂

Vous pouvez
- [ ] Effacez les lignes d'explications ci-dessus
- [ ] Expliquer les modifications pour faciliter la relecture
- [ ] Lancer un appel à review sur le channel #incubateur-site sur Slack

2020-09-24 13:07 UTC, Morendil commented on content/_authors/stanislas.ormieres.md
> +    employer: Moi-même (porté par Econocom) # si applicable, le nom de ton administration, SSII, etc.
Dans ce cas c'est plutôt `status: independent` et `employer: Econocom`

2020-09-24 13:09 UTC, Morendil requested changes

2020-09-24 13:09 UTC, Morendil commented on content/_authors/stanislas.ormieres.md
> +    - Candilib # le nom du fichier de la startup dans le répertoire /content/_startups/ sans l'extension .md
Ici ce sont des id donc en minusciles (`candilib`, `psij`)

2020-09-24 13:09 UTC, Morendil commented on content/_authors/stanislas.ormieres.md
> +github: pseudo_github # optionnel : nom d'utilisateur GitHub, permet d'être ajouté automatiquement à l'organisation GitHub betagouv
Il vaut mieux ne pas laisser la valeur exemple ici :)

2020-09-24 13:13 UTC, laruiss commented on content/_authors/stanislas.ormieres.md
> +    employer: Moi-même (porté par Econocom) # si applicable, le nom de ton administration, SSII, etc.
OK, corrigé

2020-09-24 13:13 UTC, laruiss commented on content/_authors/stanislas.ormieres.md
> +    - Candilib # le nom du fichier de la startup dans le répertoire /content/_startups/ sans l'extension .md
Corrigé

2020-09-24 13:13 UTC, laruiss commented on content/_authors/stanislas.ormieres.md
> +github: pseudo_github # optionnel : nom d'utilisateur GitHub, permet d'être ajouté automatiquement à l'organisation GitHub betagouv
Ah, oui, en effet...

2020-09-24 13:56 UTC, Morendil approved these changes

2020-09-24 13:59 UTC, Morendil commented
Bienvenue Stanislas !

Je peux merger en l'état, et au passage je remarque que pour ta bio tu as gardé le texte d'exemple ("Écrit des autobiographies percutantes en moins de 200 caractères depuis 1972"); tu n'es pas le seul (8 autres personnes sont dans ce cas) et j'ai envie de te proposer de la mettre à jour si c'est important pour toi de personnaliser cette partie.

2020-09-24 19:53 UTC, laruiss commented
Ah, et bien je n'avais pas compris ce qu'était cette partie. Je comprends
désormais.

Je fais ça demain matin, rien ne presse.

Merci pour la précision !

Stan

-- 
Stanislas Ormières
Stormier SARL
06 41 69 15 98

Le jeu. 24 sept. 2020 à 16:00, Laurent Bossavit <notifications@github.com>
a écrit :

> Bienvenue Stanislas !
>
> Je peux merger en l'état, et au passage je remarque que pour ta bio tu as
> gardé le texte d'exemple ("Écrit des autobiographies percutantes en moins
> de 200 caractères depuis 1972"); tu n'es pas le seul (8 autres personnes
> sont dans ce cas) et j'ai envie de te proposer de la mettre à jour si c'est
> important pour toi de personnaliser cette partie.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/betagouv/beta.gouv.fr/pull/4314#issuecomment-698363291>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAS7BGHIJGW6NAYGJXMLNADSHNGGPANCNFSM4RYI3FUA>
> .
>

2020-10-01 10:11 UTC, Morendil commented
Hello @laruiss - dis-moi si je peux merger comme tel ou si tu souhaites mettre à jour la bio ?

2020-10-01 13:05 UTC, Morendil commented
Nickel !

2020-10-01 13:08 UTC, merged