Update jean-michel.armand.md
betagouv/beta.gouv.fr pull request #4587
Opened 2020-11-16 09:30 UTC by mrjmad

🙂

Pour la review :
- [ ] Les tests passent (avec un check vert)
Si c'est une fiche de membre : 
- [ ] Les commentaires ont été effacés du fichier
- [ ] Les dates de fin correspondent à un contrat, convention ou budget validé
- [ ] Les dates de fin sont après les dates de début
- [ ] Les fiches auteurs sont dans content/_authors/
Si c'est une fiche produit ou une offre de recrutement : 
- [ ] Le problème exprimé est compréhensible par lecteur externe à la communauté
- [ ] Les recommandations de contribution sont prises en compte https://doc.incubateur.net/communaute/contribuer/recommandations
  - [ ] Éviter le jargon
  - [ ] Phrases neutres en genre
  

:warning: Pour une simple mise à jour de dates de mission, tu peux merger toi-même sans relecture (tu auras juste à attendre 1-2 mins pour les tests passent)  
PS : Ne t'attends pas à ce qu'on le fasse pour toi !

2020-11-16 09:36 UTC, Morendil requested changes
Les entrées dans `startups` prennent les identifiants courts du produit (identiques aux slugs des pages produit, e.g. https://beta.gouv.fr/startups/aidantsconnect.html -> `aidantsconnect`)

D'habitude au changement de mission, on renseigne la date de fin de ta mission précédente et on ajoute une nouvelle mission, en reportant les participations aux produits précédents dans `previously` (collection qui a le même format que `startups`).

2020-12-16 21:41 UTC, jdauphant commented on content/_authors/jean-michel.armand.md
> +  - start: 2020-10-28
@mrjmad  je ne comprends pas, tu as fait une mission en 2018 ?
ça donnerait :
```
missions:
  - start: 2018-12-21
    end: 20XX-XX-XX # compléter la date de fin et supprimer ce commentaire
    status: independent
  - start: 2020-10-28	    	    
    end: 2021-03-31
    status: independent	    
```

2020-12-17 01:24 UTC, mrjmad commented on content/_authors/jean-michel.armand.md
> +  - start: 2020-10-28
je n'avais pas l'impression qu'on gardait l'historique dans mission. c'est bon j'ai à priori modifié pour que cela soit enfin correct !

2020-12-17 13:38 UTC, jdauphant commented on content/_authors/jean-michel.armand.md
> +  - start: 2020-10-28
On a ajouté l'historique, il y a ~2ans

2020-12-17 13:38 UTC, jdauphant approved these changes

2020-12-17 13:41 UTC, merged