Création de archifiltre dans Produit !
betagouv/beta.gouv.fr pull request #4606
Opened 2020-11-19 14:36 UTC by ChloeMoser

Automatically generated by Netlify CMS

2020-11-23 11:32 UTC, LeryJ commented
Nous sommes en train de finaliser la fiche produit d'Archifiltre avec @ChloeMoser.
On est preneur de retours de la communauté.
@Morendil , je pense que ton avis sera bénéfique au regard de ton expérience ;-)

2020-11-24 17:00 UTC, Morendil commented
Merci @LeryJ et salut @ChloeMoser - je regarde ça très prochainement, n'hésite pas à me faire signe sur Slack entre-temps. (Ou pour me relancer si je tarde trop !)

2020-11-27 01:16 UTC, jdauphant commented
J'ai corrigé le bug, il y avait "commitee" dans les tests au lieu de "committee".

2020-11-27 08:44 UTC, LeryJ commented
Merci @julien mais du coup la fiche n'apparait plus dans Netlify... C'est compliqué tout ça (je le prends avec le sourire).
@ChloeMoser je suis désolé. Tu peux donc consulter ta fiche dans "files change".

2020-11-27 08:45 UTC, LeryJ commented
Le lien renvoi vers Mes aides : https://beta.gouv.fr/admin/#/collections/startups/entries/archifiltre

2020-11-27 08:48 UTC, jdauphant commented
:( décidément Netlify n'est pas très accomodant. Vous pouvez continuer sur file changed. (on peut essayer de couper les PR mais je ne suis pas sûr que ça marche ensuite dans Netlify)

2020-11-27 08:55 UTC, ChloeMoser commented
Merci @jdauphant je suis rassurée si le texte de la fiche est toujours là! N'hésite pas à me dire ce que je dois modifier ou compléter sur la fiche!

2020-11-27 08:56 UTC, ChloeMoser commented
Je suis désolée, ce sont mes 1ers pas sur github, je ne maîtrise pas trop les choses...

2020-11-27 09:09 UTC, Morendil commented
@ChloeMoser Pas de souci, l'avantage des systèmes de versionnement c'est qu'il y a très peu d'erreurs irréversibles :)

2020-11-27 09:14 UTC, Morendil commented on content/_startups/archifiltre.md
> +\- des espaces serveur surchargés qui coûtent inutilement en terme de stockage (coût financier et écologique),
Utiliser de préférence les listes à puce de Markdown:
```
- des espaces serveur, etc.
- une grande difficulté, etc.
```
(pas de sauts de lignes entre les éléments de la liste et supprimer l'anti-slash avant le tiret)

2020-11-27 09:15 UTC, Morendil commented on content/_startups/archifiltre.md
> +Les professionnel.le.s de l'information (dont environ 5000 archivistes exerçant dans le secteur public) ont pour mission de traiter cette production exponentielle. Sans outil adapté, ils/elles étaien
Préférer le point médian ·
stratégique -> stratégiques

2020-11-27 09:18 UTC, julien commented
Finir chaque phrase avec un point d’exclamation ça donne l'impression que la personne qui écrit est en train de crier en même temps :joy: . Bonne journée à vous.

2020-11-27 09:40 UTC, ChloeMoser commented on content/_startups/archifiltre.md
> +\- des espaces serveur surchargés qui coûtent inutilement en terme de stockage (coût financier et écologique),
OK, je vois avec mes collègues comment modifier ça

2020-11-27 09:40 UTC, ChloeMoser commented on content/_startups/archifiltre.md
> +Les professionnel.le.s de l'information (dont environ 5000 archivistes exerçant dans le secteur public) ont pour mission de traiter cette production exponentielle. Sans outil adapté, ils/elles étaien
OK pour le point médian.
Pour le stratégique c'était pour aller avec information

2020-11-27 09:41 UTC, ChloeMoser commented
Merci beaucoup Julien, j'ai effectivement tendance à user/abuser du point d'exclamation! Je corrige tout ça! ;-)

2020-11-27 10:03 UTC, Morendil requested changes
"Request changes" pour les 2 PR au lieu d'une.

2020-11-27 10:04 UTC, Morendil commented on content/_startups/archifiltre.md
> +Les professionnel.le.s de l'information (dont environ 5000 archivistes exerçant dans le secteur public) ont pour mission de traiter cette production exponentielle. Sans outil adapté, ils/elles étaien
Ah oui :)

2020-11-27 10:49 UTC, ChloeMoser commented on content/_startups/archifiltre.md
> +# Notre solution
La page stats est en cours de réalisation sur le site. On la mettre en lien dès qu'elle sera en ligne.
La 1ère cible était les archivistes, même si sur les 5000, peu sont concernés par le numérique encore. Mais nous avons élargi notre cible plus largement à tous les professionnels de l'information puis tous les possesseurs d'ordinateur qui enregistrent des documents. 
Merci pour ces pistes que je vais essayer d'illustrer davantage dans la fiche du coup!

2020-11-30 09:02 UTC, ChloeMoser commented on content/_startups/archifiltre.md
> +# Notre solution
Bonjour @Morendil on peut fermer cette discussion et renvoyer vers la page Stats en cours de réalisation ou il faudrait compléter certains éléments sur la fiche?

2020-11-30 09:39 UTC, ChloeMoser commented on content/_startups/archifiltre.md
> +# Notre solution
Nous avons par exemple ce genre d'éléments: "Sur une étude réalisée sur nos utilisateurs en novembre 2020 : 
50% des utilisateurs l'utilisent plusieurs fois par semaine
47% plusieurs fois par mois
3% tous les jours
Par ailleurs, les 2/3 des répondants jugent  le produit désormais "indispensable". Les principales raisons évoquées sont l'aspect tout-en-un de l'outil (avant, ils étaient obligés d'utiliser plusieurs outils différents et considérés comme moins performants pour aboutir au même résultat) et les fonctionnalités avancées (repérage des doublons en un clin d'oeil, rapport d'audit, export csv hiérarchisé,...) qui leur permettent un gain de temps avéré et une efficacité certaine dans leur travail quotidien."
Mais je pense que c'est trop détaillé pour l'instant pour les afficher sur la fiche et qu'il vaut mieux renvoyer à la page de statistiques.
Idem pour les éléments comparatifs avec d'autres outils équivalents: est-ce à indiquer au niveau de la fiche betagouv?

2020-11-30 14:30 UTC, Morendil commented
Bonjour @ChloeMoser pour moi les éléments bloquants pour cette PR sont techniques, c'est de la part de @jdauphant que j'attends une intervention - Julien si tu veux bien séparer en 2 PR pour qu'on aie dans celle-ci que de la fiche produit ?

Bien que ce ne soit pas bloquant, je t'invite à voir les remarques que j'ai apportées sur le fond comme un processus qui démarre, plutôt que comme un événement ponctuel "revue et publication de la fiche".

Nous sommes à votre disposition ("nous" étant @LeryJ en tant que personne référente, l'équipe de co-animation de beta.gouv.fr, et au-delà, toute la communauté beta avec des compétences très diverses) pour venir en soutien. Notre préoccupation avec le site beta.gouv.fr c'est de rendre compte de la mise en oeuvre d'une nouvelle façon de déployer des politiques publiques, et plus on donne à voir d'éléments dans ce sens là, plus l'ensemble des équipes bénéficie de cette consolidation de nos pratiques.

La fiche produit n'est que la partie visible d'un iceberg dont la masse est constituée de collaborations entre nous. Par exemple on pourrait programmer un atelier commun autour de cette page de stats, ou autour de l'analyse concurrentielle de l'écosystème.

2020-11-30 19:05 UTC, jdauphant commented on content/_startups/labonneplace.md
> +  - name: committee
j'ai juste fixé ce qui bloqué le merge de leur PR. Il y a eu des commits entre temps, ça va marcher avec netlify un rebase ?

2020-12-03 08:26 UTC, LeryJ commented
Hello @ChloeMoser ,
Je pense qu'on va pouvoir publier cette fiche dès maintenant.
Vous vous êtes fixés une date limite pour publier une page stats?
Si vous avez besoin d'aide, je pense que votre coach sera bien placé pour vous aider. (D'ailleurs, je ne sais plus si vous en avez un @Eric-Hei ?).
Du côté de beta, on pourra vous aider avec plaisir mais probablement avec moins d'attention qu'un coach qui pourra vous accompagner dans le temps.
Si tout ça te convient, @ChloeMoser tu peux "squash and merge" pour publier. ;-)

2020-12-04 09:44 UTC, ChloeMoser commented
Merci beaucoup @LeryJ et tous. 
Nous préparons la page de stats pour le 19/12. Notre coach est @Eric-Hei justement ;-) 
Merci d'avoir donné la prochaine étape. Je fais donc "squash and merge".

2020-12-04 09:46 UTC, ChloeMoser commented
Ah non, je n'ai pas les droits pour cliquer sur le bouton "Squash and merge". Peut-être parce qu'il y a 1 élément qui apparait en rouge "Changes requested" @LeryJ non?

2020-12-04 10:21 UTC, Morendil commented on content/_startups/labonneplace.md
> +  - name: committee
Je ne vois pas de raison pour que ça ne marche pas.

L'idée pour moi c'est
- séparer dans une PR à part la correction technique `commitee` -> `committee`
- soit merger la PR corrective dans un premier temps, puis rebaser celle-ci
- soit retirer de celle-ci le "fix" plus ambitieux, et simplement corriger `committee` en `commitee`, merger, puis passer la PR corrective

2020-12-04 10:23 UTC, Morendil commented
@ChloeMoser Comme je disais plus haut, le "Changes requested" apparait parce que j'ai demandé à @jdauphant de ré-intervenir sur cette PR pour qu'elle soit conforme à un standard de qualité technique (ne pas mélanger plusieurs sujets dans une PR) qui n'a rien à voir avec le contenu de la fiche produit; désolé pour le délai induit.

2020-12-04 11:29 UTC, ChloeMoser commented
Ok merci beaucoup pour ces réponses. Sinon, il y a une alerte "This branch is out-of-date with the base branch" et un bouton "Update branch" sur lequel je peux cliquer.

2020-12-04 17:23 UTC, merged