Correction du menu Formation
betagouv/beta.gouv.fr pull request #4737
Opened 2020-12-15 15:38 UTC by jdauphant

🙂

Pour la review :
- [ ] Les tests passent (avec un check vert)

2020-12-16 18:04 UTC, jdauphant commented
@CamilleGarrigue tu peux tester et valider la modif si le rendu te vas : https://deploy-preview-4737--beta-gouv-fr.netlify.app/approche/

2020-12-17 08:49 UTC, Morendil requested changes
Cette PR introduit une régression quand on navigue dans les sous-parties de "La formation en ligne", le menu disparait et il faut le déplier à nouveau à chaque fois.

2020-12-17 19:01 UTC, Morendil approved these changes

2020-12-17 19:04 UTC, jdauphant commented
Ah bah, j'allais t'envoyer un message ^^

2020-12-17 19:11 UTC, merged