Mise à jour de justif dans Produit
betagouv/beta.gouv.fr pull request #5743
Opened 2021-04-23 13:58 UTC by Sw1n

Passage du produit en construction 🙂

Pour la review :
- [ ] Les tests passent (avec un check vert)
Si c'est une fiche de membre : 
- [ ] Les commentaires ont été effacés du fichier
- [ ] Les dates de fin correspondent à un contrat, convention ou budget validé
- [ ] Les dates de fin sont après les dates de début
- [ ] Les fiches auteurs sont dans content/_authors/
Si c'est une fiche produit ou une offre de recrutement : 
- [ ] Le problème exprimé est compréhensible par une personne externe à la communauté
- [ ] Les recommandations de contribution sont prises en compte https://doc.incubateur.net/communaute/contribuer/recommandations
  - [ ] Éviter le jargon
  - [ ] Phrases neutres en genre
  

:warning: Pour une simple mise à jour de dates de mission, tu peux merger toi-même sans relecture (tu auras juste à attendre 1-2 mins pour les tests passent)  
PS : Ne t'attends pas à ce qu'on le fasse pour toi !

2021-04-28 06:55 UTC, Flightan requested changes

2021-04-28 06:55 UTC, Flightan commented on content/_startups/justif.md
> +    start: 2021-03-31
@Sw1n tu supprime l'historique de la phase d'investigation exprès ou bien par erreur ?

Si elle a eu lieu, il faut plutôt garder les deux lignes:
```  
- name: investigation
    start: 2020-10-04
```

 et ajouter la nouvelle phase.

2021-05-04 16:42 UTC, Sw1n commented on content/_startups/justif.md
> +    start: 2021-03-31
Effectivement c'était une erreur ! Je corrige du coup

2021-05-05 06:59 UTC, LeryJ approved these changes

2021-05-05 07:01 UTC, merged

2021-05-05 07:41 UTC, Sw1n commented on content/_startups/justif.md
> +Parmi les premières hypothèses à tester - qui pourront être challengées avec toi au fil de l’eau - nous prévoyons :
On corrige ça, merci Lery

2021-05-05 07:41 UTC, Sw1n commented on content/_startups/justif.md
> +Parmi les premières hypothèses à tester - qui pourront être challengées avec toi au fil de l’eau - nous prévoyons :
On corrige ça, merci Lery !

2021-05-05 07:55 UTC, LeryJ commented on content/_startups/justif.md
> +Parmi les premières hypothèses à tester - qui pourront être challengées avec toi au fil de l’eau - nous prévoyons :
Je l'ai fait ;-)