Update preuve-de-covoiturage.md
betagouv/beta.gouv.fr pull request #5751
Opened 2021-04-23 17:05 UTC by charlesimone

2021-04-27 07:35 UTC, jdauphant approved these changes

2021-04-28 06:35 UTC, margot-sanchez requested changes

2021-04-28 06:35 UTC, margot-sanchez commented on content/_startups/preuve-de-covoiturage.md
>  Les Autorités Organisatrices de la Mobilité (AOM) et acteurs locaux suivent avec un intérêt croissant ces nouveaux services pouvant représenter des solutions de mobilité nouvelles et complémentaires
Lorsqu'une incitation.

Incitatif est un anglicisme, je pensais l'avoir enlevé partout

2021-04-28 06:35 UTC, margot-sanchez commented on content/_startups/preuve-de-covoiturage.md
>  - Incitation financière via la prise en charge totale ou partielle du trajet.
On met un ; en fin d'itération :)

2021-04-28 06:35 UTC, margot-sanchez commented on content/_startups/preuve-de-covoiturage.md
>  - Accès à des places de stationnement réservées ou à tarif préférentiel.
tu as enlevé les places de piscine ?

2021-04-28 06:41 UTC, margot-sanchez approved these changes

2021-04-28 06:42 UTC, merged