Update and rename mission-apprentissage.md to mission-interministérie…
betagouv/beta.gouv.fr pull request #5791
Opened 2021-04-30 09:39 UTC by Julianne-Lagadec

…lle-pour-l-apprentissage.md

Nous souhaitions repositionner "interministériel" dans le nom de la Mission car cette particularité est importante pour comprendre les fondements et l'évolution de nos travaux. Il va donc me falloir modifier les fiches de nos produits pour qu'elles soient bien rattachées à l'incubateur, j'espère ne pas faire d'erreurs.

🙂

## Publication

`beta.gouv.fr` est un site qui ne ressemble pas aux sites administratifs classiques, tout comme les produits qu'il porte.

Cependant, en tant que domaine en `.gouv`, les communications qui y sont faites engagent la responsabilité de l'administration qui héberge l'Incubateur. Toute personne proposant du contenu à publier sur `beta.gouv.fr` doit donc être pleinement consciente que les élasticités règlementaires qui nous permettent de fonctionner ne peuvent exister qu'avec une forme d'auto-régulation. **Demandez l'avis de membres plus anciens que vous avant de publier du contenu.**

## Review
Si c'est une fiche de membre : 
- [ ] Les dates de fin correspondent à un contrat, convention ou budget validé
- [ ] Les dates de fin sont après les dates de début
- [ ] Les fiches auteurs sont dans content/_authors/
Si c'est une fiche produit ou une offre de recrutement : 
- [ ] Le problème exprimé est compréhensible par une personne externe à la communauté
- [ ] Les recommandations de contribution sont prises en compte https://doc.incubateur.net/communaute/contribuer/recommandations
  - [ ] Éviter le jargon
  - [ ] Phrases neutres en genre
  
## Mise à jour de date de mission
:warning: Pour une simple mise à jour de dates de mission, tu peux merger toi-même sans relecture (tu auras juste à attendre 1-2 mins pour les tests passent)  
PS : Ne t'attends pas à ce qu'on le fasse pour toi !

2021-05-03 10:58 UTC, jdauphant requested changes
@Julianne-Lagadec "mission-apprentissage" est l'identifiant technique de l'incubateur ça doit même correspondre partout où il est référencé : https://github.com/betagouv/beta.gouv.fr/search?q=%22mission-apprentissage%22

Vous pouvez très bien avoir un nom d'affichage différent est plus complet que l'identifiant technique "mission-apprentissage"

2021-05-03 11:11 UTC, Julianne-Lagadec commented
Bonjour, ok donc j'ai tout fait mal ensuite pour les modifications des
pages Startup reliées à l'incubateur. Je suis désolée de ce dérangement.
C'est possible d'annuler mes requêtes et que j'en fasse de nouvelles
correctes ?
Merci !

Le lun. 3 mai 2021 à 12:58, Julien DAUPHANT ***@***.***> a
écrit :

> ***@***.**** requested changes on this pull request.
>
> @Julianne-Lagadec <https://github.com/Julianne-Lagadec>
> "mission-apprentissage" est l'identifiant technique de l'incubateur ça doit
> même correspondre partout où il est référencé :
> https://github.com/betagouv/beta.gouv.fr/search?q=%22mission-apprentissage%22
>
> Vous pouvez très bien avoir un nom d'affichage différent est plus complet
> que l'identifiant technique "mission-apprentissage"
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/betagouv/beta.gouv.fr/pull/5791#pullrequestreview-650254211>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ATLFKM77DT3T3GLJE37KTSLTLZ6XDANCNFSM43325F3A>
> .
>

2021-05-03 11:42 UTC, jdauphant commented
Pour les accents, on préfère eviter dans le nom technique aussi. Ça serait peut-être plus pratique qu'on regarde ça ensemble.

2021-05-03 11:42 UTC, jdauphant commented
Sur Slack dans mon profil, tu as un lien pour réservé un créneau dans mon agenda

2021-05-03 11:46 UTC, jdauphant commented
Je viens de regrouper ensemble toutes les modifications.

2021-05-03 11:50 UTC, Julianne-Lagadec commented
Ok, j'ai réservé le créneau de 17h qui était proposé dans ton agenda. À
tout à l'heure.

Le lun. 3 mai 2021 à 13:46, Julien DAUPHANT ***@***.***> a
écrit :

> Je viens de regrouper ensemble toutes les modifications.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/betagouv/beta.gouv.fr/pull/5791#issuecomment-831207882>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ATLFKM3W3ACLFF52C26LQUTTL2EKHANCNFSM43325F3A>
> .
>

2021-05-03 15:15 UTC, jdauphant commented on content/_startups/catalogue.des.formations.en.apprentissage.md
> +owner: Mission interministérielle pour l'apprentissage
Peut être renommer "catalogue.des.formations.en.apprentissage" -> "catalogue.apprentissage"
```suggestion
owner: Mission interministérielle pour l'apprentissage
redirect_from:
  - /startups/catalogue.des.formations.en.apprentissage.md 
```

2021-05-03 15:17 UTC, jdauphant commented on content/_startups/tableau-de-bord-apprentissage.md
> +repository: https://github.com/mission-apprentissage/prise-de-rdv
Je pense qu'il y a une erreur

2021-05-03 15:17 UTC, jdauphant commented on content/_startups/tableau-de-bord-apprentissage.md
> +    start:
Manque la date

2021-05-05 08:19 UTC, Julianne-Lagadec reviewed
Les changements demandés ont normalement été effectué. J'ai supprimé Matcha (je voulais juste supprimer les modifs pour les faire plus tard) sans faire exprès.
Merci !

2021-05-05 12:09 UTC, jdauphant approved these changes

2021-05-05 12:11 UTC, merged