Création de 2021-06-21-beta-gouv.recrute.une.ou.un.lead.developpeuse.ou.developpeur.senior-.1 dans Fiche de poste !
betagouv/beta.gouv.fr pull request #6313
Opened 2021-06-21 13:18 UTC by nathalie-reyre

Automatically generated by Netlify CMS

2021-06-21 21:32 UTC, jdauphant commented on content/_jobs/2021-06-21-beta-gouv.recrute.une.ou.un.lead.developpeuse.ou.developpeur.senior-.1.md
> +
@nathalie-reyre tu as gardé l'exemple

2021-06-21 21:33 UTC, jdauphant commented on content/_jobs/2021-06-21-beta-gouv.recrute.une.ou.un.lead.developpeuse.ou.developpeur.senior-.1.md
> +roles: "Beta.gouv recrute une ou un lead développeuse ou développeur sénior. "
Il faudrait préciser où est le poste dans le titre

2021-06-22 07:37 UTC, nathalie-reyre commented on content/_jobs/2021-06-21-beta-gouv.recrute.une.ou.un.lead.developpeuse.ou.developpeur.senior-.1.md
> +
au temps pour moi. A supprimer en effet

2021-06-22 07:41 UTC, nathalie-reyre commented on content/_jobs/2021-06-21-beta-gouv.recrute.une.ou.un.lead.developpeuse.ou.developpeur.senior-.1.md
> +
J'ai corrigé la fiche. Je pense que c'est tout bon

2021-06-22 07:59 UTC, jdauphant commented on content/_jobs/2021-06-21-beta-gouv.recrute.une.ou.un.lead.developpeuse.ou.developpeur.senior-.1.md
> +Afin de lancer un service autour des immersions professionnelles, beta.gouv, recherche un·e lead développeur·euse senior, de préférence Python/JS (React, Node.js)/PostgreSQL/API Rest. 
Python et JS  ou Python ou JS ?  
il y a déjà des contraintes pour fixer les technologies dès le début ? (tu auras moins de candidats s'ils ne peuvent pas choisir les technos)
Surtout que juste en dessous, c'est plus ouvert avec "Stack à définir avec toi".

Aussi la description du produit est très bréve, c'est dur de se projeter

2021-06-24 09:14 UTC, nathalie-reyre commented on content/_jobs/2021-06-21-beta-gouv.recrute.une.ou.un.lead.developpeuse.ou.developpeur.senior-.1.md
> +Afin de lancer un service autour des immersions professionnelles, beta.gouv, recherche un·e lead développeur·euse senior, de préférence Python/JS (React, Node.js)/PostgreSQL/API Rest. 
le produit n'est pas encore officiellement lancé et notre financeur avait des hésitations donc je ne voulais pas le brusquer. C'est bon maintenant pour en dire plus. Je corrige la fiche

2021-06-25 10:37 UTC, jonathanfallon requested changes

2021-06-25 10:37 UTC, jonathanfallon commented on content/_jobs/2021-06-21-beta-gouv.recrute.une.ou.un.lead.developpeuse.ou.developpeur.senior-.1.md
> +L'immersion professionnelle est un dispositif légal qui permet à tout actif occupé ou en recherche d'emploi de passer quelques jours aux côtés d'un professionnel pour découvrir un métier ou valider u
```suggestion
L'immersion professionnelle est un dispositif légal qui permet à tout actif occupé ou en recherche d'emploi de passer quelques jours aux côtés d'un professionnel pour découvrir un métier ou valider un nouveau projet professionnel. C'est un vrai facteur de réussite ! Mais aujourd'hui, ceux qui en profitent sont le plus souvent ceux qui ont le moins de difficultés à trouver un emploi. Et le traitement administratif de ce dispositif est beaucoup trop chronophage pour les conseillers qui accompagnent les bénéficiaires des immersions. Notre objectif est de simplifier le process administratif en s'appuyant sur la dématérialisation des démarches et de faciliter la recherche des immersions pour les personnes les plus éloignées de l'emploi en construisant une base qualifiée d'entreprises.
```

2021-06-25 10:37 UTC, jonathanfallon commented on content/_jobs/2021-06-21-beta-gouv.recrute.une.ou.un.lead.developpeuse.ou.developpeur.senior-.1.md
> +Tu  es en mesure de jouer sur 2 tableaux :
```suggestion
Tu es en mesure de jouer sur 2 tableaux :
```

2021-06-25 10:37 UTC, jonathanfallon commented on content/_jobs/2021-06-21-beta-gouv.recrute.une.ou.un.lead.developpeuse.ou.developpeur.senior-.1.md
> +Ne rigole pas avec la sécurité du code\
```suggestion
Sensibilisé.e à la sécurité du code\
```

2021-06-25 10:37 UTC, jonathanfallon commented on content/_jobs/2021-06-21-beta-gouv.recrute.une.ou.un.lead.developpeuse.ou.developpeur.senior-.1.md
> +* Stack à définir avec toi (On a une appétence pour les techno’ qui ont fait leurs preuves et qui permettent d’être propre, rapide et souverain : Python (Django, Flask, ..), JavaScript, TypeScript, R
```suggestion
* Stack à définir avec toi (On a une appétence pour les techno’ qui ont fait leurs preuves et qui permettent d’être propre, rapide et souverain : Python (Django, Flask, ..), JavaScript, TypeScript, React, Vue.js... ). Dans le périmètre du service, création et administration d'un formulaire en ligne avec identification numérique, création d'une base de données, création d'un moteur de recherche, flux de données via des API entrantes et sortantes (à construire).
```

2021-06-25 10:37 UTC, jonathanfallon commented on content/_jobs/2021-06-21-beta-gouv.recrute.une.ou.un.lead.developpeuse.ou.developpeur.senior-.1.md
> +* Tu  adores travailler dans une petite équipe et de manière agile, au sein d’une communauté à qui proposer et demander de l’aide ;
```suggestion
* Tu adores travailler dans une petite équipe et de manière agile, au sein d’une communauté à qui proposer et demander de l’aide ;
```

2021-06-25 10:42 UTC, nathalie-reyre commented on content/_jobs/2021-06-21-beta-gouv.recrute.une.ou.un.lead.developpeuse.ou.developpeur.senior-.1.md
> +Ne rigole pas avec la sécurité du code\
ah ah, plus politiquement correct !

2021-06-25 12:38 UTC, merged