Création de la fiche produit UrgenceVie
betagouv/beta.gouv.fr pull request #6399
Opened 2021-06-30 05:58 UTC by dlequepeys

2021-06-30 11:04 UTC, jdauphant requested changes

2021-06-30 11:04 UTC, jdauphant commented on content/_authors/frederic.auffret.md
> +---
@dlequepeys tu ne peux plus faire ça, toute nouvelle personne doit passé par le formulaire d'onboarding : https://webinaire.numerique.gouv.fr//meeting/signin/533/creator/16/hash/bc9b9260ce232516af185551e4e32cf6b798c9c8

2021-06-30 16:17 UTC, LeryJ commented on content/_authors/frederic.auffret.md
> +---
+1

2021-06-30 16:29 UTC, LeryJ approved these changes

2021-07-01 07:27 UTC, LeryJ commented on content/_authors/frederic.auffret.md
> +---
Le bon lien d'onboarding : https://secretariat.incubateur.net/onboarding

2021-07-02 13:53 UTC, merged