Mise à jour de raphaelle.gaillard dans Membre
betagouv/beta.gouv.fr pull request #6445
Opened 2021-07-05 15:41 UTC by RaphBeta

Automatically generated by Netlify CMS

2021-07-05 17:39 UTC, jdauphant requested changes

2021-07-05 17:39 UTC, jdauphant commented on content/_authors/raphaelle.gaillard.md
> -    employer: pole-emploi
@rachidLBP tu ne peux pas changer le status, tu dois ajouter une nouvelle entrée dans "misions" et gardé l'ancienne entrée Pôle Emploi

cc @adenoix

2021-07-06 07:12 UTC, tyjak commented on content/_authors/raphaelle.gaillard.md
> -    employer: pole-emploi
@jdauphant Je ne crois pas que cela concerne @rachidLBP mais @RaphBeta

2021-07-06 07:41 UTC, jdauphant commented on content/_authors/raphaelle.gaillard.md
> -    employer: pole-emploi
Oui en effet, dsl Rachid

2021-07-30 12:48 UTC, adenoix approved these changes

2021-07-30 12:48 UTC, merged