Finetune intra
betagouv/beta.gouv.fr pull request #6512
Opened 2021-07-09 18:21 UTC by renardpal

dans Jobs : j'ai rajouté du margin-top sur le CTA de la card intra. @LucasCharrier comme t'avais fait un css additionnel sur intra, j'ai reproduit même si y'a qu'une classe dedans...

dans devenir intra : fix graphiques ou syntaxiques.

2021-07-16 07:31 UTC, Flightan requested changes

2021-07-16 07:31 UTC, Flightan commented on _layouts/intrapreneur-role.html
> +                            <li><a href="#l-intra-vient-du-terrain">L’intra vient du terrain</a></li>
Je crois que tu as cassé le lien
```suggestion
                            <li><a href="#l-intrapreneur-vient-du-terrain">L’intra vient du terrain</a></li>
```

2021-07-16 07:31 UTC, Flightan commented on assets/main.css
> +/*
Tu ne veux pas juste supprimer le css ?

2021-08-18 08:47 UTC, LucasCharrier commented on assets/additional/style/jobs.css
> +}
```suggestion
}

```

2021-08-18 08:48 UTC, LucasCharrier commented on assets/additional/style/lpintra.css
>  }
```suggestion
}

```

2021-08-18 09:30 UTC, merged