Update marion.guillet.md
betagouv/beta.gouv.fr pull request #7084
Opened 2021-09-15 13:33 UTC by guilletmarion

🙂

## Publication

`beta.gouv.fr` est un site qui ne ressemble pas aux sites administratifs classiques, tout comme les produits qu'il porte.

Cependant, en tant que domaine en `.gouv`, les communications qui y sont faites engagent la responsabilité de l'administration qui héberge l'Incubateur. Toute personne proposant du contenu à publier sur `beta.gouv.fr` doit donc être pleinement consciente que les élasticités règlementaires qui nous permettent de fonctionner ne peuvent exister qu'avec une forme d'auto-régulation. **Demandez l'avis de membres plus anciens que vous avant de publier du contenu.**

## Review
Si c'est une fiche de membre : 
- [ ] Les dates de fin correspondent à un contrat, convention ou budget validé
- [ ] Les dates de fin sont après les dates de début
- [ ] Les fiches auteurs sont dans content/_authors/
Si c'est une fiche produit ou une offre de recrutement : 
- [ ] Le problème exprimé est compréhensible par une personne externe à la communauté
- [ ] Les recommandations de contribution sont prises en compte https://doc.incubateur.net/communaute/contribuer/recommandations
  - [ ] Éviter le jargon
  - [ ] Phrases neutres en genre
  
## Mise à jour de date de mission
:warning: Pour une simple mise à jour de dates de mission, tu peux merger toi-même sans relecture (tu auras juste à attendre 1-2 mins pour les tests passent)  
PS : Ne t'attends pas à ce qu'on le fasse pour toi !

2021-09-15 16:21 UTC, jdauphant commented on content/_authors/marion.guillet.md
> +    employer: mission-apprentissage
"mission-apprentissage" n'est pas une entité juridique.
Est-ce que tu as toujours un contrat salarié pole-emploi ?
Ou sinon tu as un autre statut, il va falloir faire une deuxième entrée dans "missions" par exemple :
```
missions:
  - start: 2019-10-21
    end: 2021-06-30
    status: admin
    employer: Pole Emploi
  - start: 2021-07-01
    end: 2022-06-30
    status: independent
    employer: Octo
```

2021-09-15 16:44 UTC, guilletmarion reviewed
Ok pour ceci alors : 

missions:
- start: 2019-10-21 
end: 2021-09-30
status: admin 
employer: Pole Emploi 
- start: 2020-06-01
end: 2022-06-30 
status: independent 
employer: UT7


(J'ai modifié les dates ainsi que l'employer indépendant)

2021-09-15 18:59 UTC, jdauphant commented
@guilletmarion  ah ça se chevauche. On peut faire commencer la deuxième mission à la fin de la première (sinon ça te compte en double dans l'historique)

2021-09-20 12:59 UTC, adenoix requested changes

2021-09-20 12:59 UTC, adenoix commented on content/_authors/marion.guillet.md
> +    employer: Pole Emploi
il faut garder la forme "pole-emploi" 
```suggestion
    employer: pole-emploi
```

2021-09-20 13:06 UTC, guilletmarion commented
ok pour moi pour les modifs d'Arnaud.

2021-09-20 13:07 UTC, jdauphant commented
@guilletmarion @adenoix la correction à faire est sur les dates de mission qui se chevauche

2021-09-20 14:12 UTC, guilletmarion commented
Bonjour, C'est normal, je travaillais sur les deux services pendant un long moment (et jusqu'à fin septembre)

2021-09-20 16:06 UTC, adenoix approved these changes

2021-09-20 16:07 UTC, merged