new job API Entreprise
betagouv/beta.gouv.fr pull request #7116
Opened 2021-09-20 10:34 UTC by Haelle

Ajout de la fiche de poste de développeur pour API Entreprise sur beta.gouv.fr.

Fiche d'origine [ici](https://place-emploi-public.gouv.fr/offre-emploi/developpeur-full-stack-api-entreprise-hf-reference-2021-700472/)

2021-09-20 22:36 UTC, jdauphant requested changes

2021-09-20 22:36 UTC, jdauphant commented on content/_jobs/2021-09-20-developpeur_api_entreprise.md
> +roles: Développeur full-stack API Entreprise
```suggestion
roles: Développeur - Développeuse full-stack API Entreprise
```

Il faut inclure le feminin dans "roles".
Tu as  plus de détail ici : https://doc.incubateur.net/communaute/travailler-a-beta-gouv/jutilise-les-outils-de-la-communaute/gitbook/recommandations#syntaxe

2021-09-20 22:36 UTC, jdauphant commented on content/_jobs/2021-09-20-developpeur_api_entreprise.md
> +title: Développeur full-stack API Entreprise
Normalement ce champ n'existe pas
```suggestion
```

2021-09-21 11:54 UTC, jdauphant commented on content/_jobs/2021-09-20-developpeur_api_entreprise.md
> +Poste ouvret en CDD. Le télétravail est possible. Démarrage octobre/novembre 2021.
```suggestion
Poste ouvert en CDD. Le télétravail est possible. Démarrage octobre/novembre 2021.
```

2021-09-21 11:54 UTC, jdauphant approved these changes

2021-09-21 13:32 UTC, jdauphant commented
@Haelle tu as les droits de merge ?
Il faut faire un PR sur ta fiche github https://github.com/betagouv/beta.gouv.fr/blob/master/content/_authors/alexis.leclerc.md avec ton compte : "github: Haelle"
Et confirmer la demande sur mattermost (pour qu'on sache que c'est bien toi) ^^

2021-09-21 13:44 UTC, Haelle commented
@jdauphant je viens de l'ajouter directement dans cette PR... c'est pas opti, mais bon c'est mineur...

J'ai déjà mergé des PRs sur mes modifications de dates de fin de mission mais là je ne peux pas apparemment

2021-09-21 13:48 UTC, jdauphant commented
Tu seras réinvité au merge.
Un bot gére les entrées/sorties.

2021-09-21 13:48 UTC, merged