Création de 2021-11-18-product.designer.user.researcher.ux.ui dans Fiche de poste !
betagouv/beta.gouv.fr pull request #7661
Opened 2021-11-18 18:54 UTC by mariannehirsch-1

Automatically generated by Netlify CMS

2021-11-19 13:35 UTC, vinyll requested changes
J'ai fait une petite relecture.
J'ai par contre pas vérifié les méta avec ce qui est interpreté

2021-11-19 13:35 UTC, vinyll commented on content/_jobs/2021-11-18-product.designer.user.researcher.ux.ui.md
> +Votre rôle sera de contribuer à la mise en place des pratiques de conception centrées utilisateur.rices et guidées par par la recherche d'impact (via le suivi d'indicateurs, de données d'utilisation,
guidées par ~~par~~ la

2021-11-19 13:35 UTC, vinyll commented on content/_jobs/2021-11-18-product.designer.user.researcher.ux.ui.md
> +L'ambition sera également de crée**r des synergies entre les différents services** qui répondent à des **problématiques similaires** et de travailler avec des collectivités de dimension et de typolog
La mise en gras est au milieu du "créer"

2021-11-19 13:35 UTC, vinyll commented on content/_jobs/2021-11-18-product.designer.user.researcher.ux.ui.md
> +## **Modalités de travail**
Pas besoin de mettre en gras les titres, il y a un style par défaut déjà

2021-11-19 13:35 UTC, vinyll commented on content/_jobs/2021-11-18-product.designer.user.researcher.ux.ui.md
> +* Parce que vous rejoindrez la communauté beta.gouv dont nous faisons partie : <https://beta.gouv.fr/> (plus de détails ici également : <https://github.com/betagouv/beta.gouv.fr/wiki/Bienvenue>) et s
produit sans "s", c'est voulu ?

2021-11-19 13:35 UTC, vinyll commented on content/_jobs/2021-11-18-product.designer.user.researcher.ux.ui.md
> +* Si vous aimé être autonome et libre
vous aimez

2021-11-19 13:35 UTC, vinyll commented on content/_jobs/2021-11-18-product.designer.user.researcher.ux.ui.md
> +* Si vous avez eu des expériences structurantes et formatrices sur la stratégie de conception de produit numérique
produits numériques au pluriel peut-être ?

2021-11-19 13:35 UTC, vinyll commented on content/_jobs/2021-11-18-product.designer.user.researcher.ux.ui.md
> +* **An tant que UX UI**, l'ambition sera de co-construire les prototypes de services qu'ils soient numériques, produits ou encore logistiques.
En tant que

2021-11-19 13:35 UTC, vinyll commented on content/_jobs/2021-11-18-product.designer.user.researcher.ux.ui.md
> +## Candidater **:**
Retirer le gras sur `:`

2021-11-19 13:35 UTC, vinyll commented on content/_jobs/2021-11-18-product.designer.user.researcher.ux.ui.md
> +Envoyez nous CV, linkedin et portfolio via le formulaire ci-dessous.
Sur le site de l'incubateur on a l'option d'incruster un formulaire, mais je ne suis pas sûr que ce soit aussi le cas sur le site de BetaGouv

2021-11-22 19:08 UTC, mariannehirsch-1 commented on content/_jobs/2021-11-18-product.designer.user.researcher.ux.ui.md
> +* Parce que vous rejoindrez la communauté beta.gouv dont nous faisons partie : <https://beta.gouv.fr/> (plus de détails ici également : <https://github.com/betagouv/beta.gouv.fr/wiki/Bienvenue>) et s
oui

2021-11-22 19:10 UTC, mariannehirsch-1 reviewed
@vinyll peux-tu merger stp j'ai fait les corrections !

2021-11-22 20:41 UTC, vinyll requested changes
Le lien Airtable est cassé

2021-11-22 20:41 UTC, vinyll commented on content/_jobs/2021-11-18-product.designer.user.researcher.ux.ui.md
> +Envoyez nous CV, linkedin et portfolio via le formulaire ci-https://airtable.com/shr5005Oj0lXyygN2.
`ci-https://…` les mots joints vont casser le lien /

2021-11-29 10:16 UTC, merged