Mise à jour de olivier.gerard dans Membre
betagouv/beta.gouv.fr pull request #7964
Opened 2021-12-10 12:49 UTC by 08071963

Automatically generated by Netlify CMS

2021-12-13 09:52 UTC, alemangui requested changes

2021-12-13 09:52 UTC, alemangui commented on content/_authors/olivier.gerard.md
> +github: Olivier G.
@08071963 est-tu sur que ton utilisateur Github est "Olivier G." ? Je ne le trouve pas sur https://github.com/Olivier%20G./

2021-12-13 10:33 UTC, 08071963 commented
BonjourJe ne comprends pas la question...Bien cordialement Olivier06 85 03 42 69 Télécharger Outlook pour AndroidDe : Alejandro M Guillén ***@***.***>Envoyé : lundi 13 décembre 2021 à 10:53À : betagouv/beta.gouv.frCc : Olivier; MentionObjet : Re: [betagouv/beta.gouv.fr] Mise à jour de olivier.gerard dans Membre (PR #7964)
@alemangui requested changes on this pull request.



In content/_authors/olivier.gerard.md:
> @@ -2,13 +2,16 @@
 fullname: Olivier GERARD
 domaine: Intraprenariat
 role: Intrapreneur REVA, Chef de projet
-github: 08071963
+github: Olivier G.

@08071963 est-tu sur que ton utilisateur Github est "Olivier G." ? Je ne le trouve pas sur https://github.com/Olivier%20G./

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

2021-12-16 10:18 UTC, LucasCharrier commented on content/_authors/olivier.gerard.md
> +github: Olivier G.
Je pense qu'il s'agit bien de @08071963 , je vais remettre cette valeur

2021-12-16 10:19 UTC, LucasCharrier commented on content/_authors/olivier.gerard.md
> +github: Olivier G.
Histoire de valider le changement de date

2021-12-16 10:22 UTC, merged